services:
  db:
    image: mysql:8.0
    container_name: db_blog
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - "${DB_PORT}:3306"
    networks:
      - blog-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app_blog
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    environment:
      - DB_CONNECTION=${DB_CONNECTION}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    networks:
      - blog-network
    depends_on:
      - db

  web:
    image: nginx:alpine
    container_name: web_blog
    restart: unless-stopped
    ports:
      - "${APP_PORT}:80"
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - blog-network
    depends_on:
      - app

volumes:
  db_data:
    driver: local
  redis_data:
    driver: local

networks:
  blog-network:
    driver: bridge